version: '3.8'
services:
  api:
    depends_on:
      - db
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
    ports:
      - 3000:3000
  db:
    container_name: ravn-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
